### ISSUE TITLE
Increase default resource allocation

### ISSUE THREAD

**Issue by mnunberg** [couchbaselabs/vagrants#18]
The current default settings call for 1 CPU and 1GB RAM. While this might be passable for normal KV operations, it is awfully painful when doing anything beyond that (be it indexing or any topology changes). Changing things to 2 CPUs and 2GB RAM seems to make things run much more smoothly (while still keeping within reason). Perhaps the default node count should also be reduced, as 2 nodes with more resources handle better than 4 nodes with less resources.

**Comment by Chippiewill** [comment]
Hi Mark,

I have opened a CBSP for this for you in JIRA:
http://issues.couchbase.com/browse/CBSP-218

Will
